# SPDX-FileCopyrightText: 2013-2024 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: LGPL-3.0-or-later

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
