var searchData=
[
  ['uilanguages_0',['uiLanguages',['https://doc.qt.io/qt-5/qlocale.html#uiLanguages',1,'QLocale']]],
  ['unblock_1',['unblock',['https://doc.qt.io/qt-5/qsignalblocker.html#unblock',1,'QSignalBlocker']]],
  ['undefined_2',['Undefined',['../classShape.html#a359229718ec54cfac5980b883e3e4ea8aec0fc0100c4fc1ce4eea230c3dc10360',1,'Shape']]],
  ['ungetchar_3',['ungetChar',['https://doc.qt.io/qt-5/qiodevice.html#ungetChar',1,'QIODevice']]],
  ['unicode_4',['unicode',['https://doc.qt.io/qt-5/qchar.html#unicode',1,'QChar::unicode() const const'],['https://doc.qt.io/qt-5/qchar.html#unicode-1',1,'QChar::unicode()'],['https://doc.qt.io/qt-5/qstring.html#unicode',1,'QString::unicode()'],['https://doc.qt.io/qt-5/qstringref.html#unicode',1,'QStringRef::unicode()'],['https://doc.qt.io/qt-5/qlatin1char.html#unicode',1,'QLatin1Char::unicode()']]],
  ['unicodeversion_5',['unicodeVersion',['https://doc.qt.io/qt-5/qchar.html#unicodeVersion',1,'QChar::unicodeVersion() const const'],['https://doc.qt.io/qt-5/qchar.html#unicodeVersion-1',1,'QChar::unicodeVersion(uint ucs4)']]],
  ['union_6',['Union',['../classShape.html#a359229718ec54cfac5980b883e3e4ea8aaef12e903e606a4895a16b393bfdec8c',1,'Shape']]],
  ['uniquekeys_7',['uniqueKeys',['https://doc.qt.io/qt-5/qhash.html#uniqueKeys',1,'QHash::uniqueKeys()'],['https://doc.qt.io/qt-5/qmap.html#uniqueKeys',1,'QMap::uniqueKeys() const const']]],
  ['unite_8',['unite',['https://doc.qt.io/qt-5/qmap.html#unite',1,'QMap::unite()'],['https://doc.qt.io/qt-5/qhash.html#unite',1,'QHash::unite()'],['https://doc.qt.io/qt-5/qset.html#unite',1,'QSet::unite()'],['https://doc.qt.io/qt-5/qrect-obsolete.html#unite',1,'QRect::unite()'],['https://doc.qt.io/qt-5/qrectf-obsolete.html#unite',1,'QRectF::unite()']]],
  ['united_9',['united',['https://doc.qt.io/qt-5/qrect.html#united',1,'QRect::united()'],['https://doc.qt.io/qt-5/qrectf.html#united',1,'QRectF::united()']]],
  ['unitvector_10',['unitVector',['https://doc.qt.io/qt-5/qlinef.html#unitVector',1,'QLineF']]],
  ['unknownoptionnames_11',['unknownOptionNames',['https://doc.qt.io/qt-5/qcommandlineparser.html#unknownOptionNames',1,'QCommandLineParser']]],
  ['unload_12',['unload',['https://doc.qt.io/qt-5/qlibrary.html#unload',1,'QLibrary::unload()'],['https://doc.qt.io/qt-5/qpluginloader.html#unload',1,'QPluginLoader::unload()']]],
  ['unlock_13',['unlock',['https://doc.qt.io/qt-5/qsharedmemory.html#unlock',1,'QSharedMemory::unlock()'],['https://doc.qt.io/qt-5/qwritelocker.html#unlock',1,'QWriteLocker::unlock()'],['https://doc.qt.io/qt-5/qreadlocker.html#unlock',1,'QReadLocker::unlock()'],['https://doc.qt.io/qt-5/qreadwritelock.html#unlock',1,'QReadWriteLock::unlock()'],['https://doc.qt.io/qt-5/qlockfile.html#unlock',1,'QLockFile::unlock()'],['https://doc.qt.io/qt-5/qmutexlocker.html#unlock',1,'QMutexLocker::unlock()'],['https://doc.qt.io/qt-5/qmutex.html#unlock',1,'QMutex::unlock()']]],
  ['unmap_14',['unmap',['https://doc.qt.io/qt-5/qfiledevice.html#unmap',1,'QFileDevice']]],
  ['unregistereventnotifier_15',['unregisterEventNotifier',['https://doc.qt.io/qt-5/qabstracteventdispatcher.html#unregisterEventNotifier',1,'QAbstractEventDispatcher']]],
  ['unregisterresource_16',['unregisterResource',['https://doc.qt.io/qt-5/qresource.html#unregisterResource',1,'QResource::unregisterResource(const QString &amp;rccFileName, const QString &amp;mapRoot)'],['https://doc.qt.io/qt-5/qresource.html#unregisterResource-1',1,'QResource::unregisterResource(const uchar *rccData, const QString &amp;mapRoot)']]],
  ['unregisterservice_17',['unregisterService',['https://doc.qt.io/qt-5/qbluetoothserviceinfo.html#unregisterService',1,'QBluetoothServiceInfo']]],
  ['unregistersocketnotifier_18',['unregisterSocketNotifier',['https://doc.qt.io/qt-5/qabstracteventdispatcher.html#unregisterSocketNotifier',1,'QAbstractEventDispatcher']]],
  ['unregistertimer_19',['unregisterTimer',['https://doc.qt.io/qt-5/qabstracteventdispatcher.html#unregisterTimer',1,'QAbstractEventDispatcher']]],
  ['unregistertimers_20',['unregisterTimers',['https://doc.qt.io/qt-5/qabstracteventdispatcher.html#unregisterTimers',1,'QAbstractEventDispatcher']]],
  ['unsetdevice_21',['unsetDevice',['https://doc.qt.io/qt-5/qdatastream-obsolete.html#unsetDevice',1,'QDataStream']]],
  ['unseterror_22',['unsetError',['https://doc.qt.io/qt-5/qfiledevice.html#unsetError',1,'QFileDevice']]],
  ['updatecurrenttime_23',['updateCurrentTime',['https://doc.qt.io/qt-5/qparallelanimationgroup.html#updateCurrentTime',1,'QParallelAnimationGroup::updateCurrentTime()'],['https://doc.qt.io/qt-5/qpauseanimation.html#updateCurrentTime',1,'QPauseAnimation::updateCurrentTime()'],['https://doc.qt.io/qt-5/qvariantanimation.html#updateCurrentTime',1,'QVariantAnimation::updateCurrentTime()'],['https://doc.qt.io/qt-5/qsequentialanimationgroup.html#updateCurrentTime',1,'QSequentialAnimationGroup::updateCurrentTime()'],['https://doc.qt.io/qt-5/qabstractanimation.html#updateCurrentTime',1,'QAbstractAnimation::updateCurrentTime()']]],
  ['updatecurrentvalue_24',['updateCurrentValue',['https://doc.qt.io/qt-5/qvariantanimation.html#updateCurrentValue',1,'QVariantAnimation::updateCurrentValue()'],['https://doc.qt.io/qt-5/qpropertyanimation.html#updateCurrentValue',1,'QPropertyAnimation::updateCurrentValue()']]],
  ['updatedirection_25',['updateDirection',['https://doc.qt.io/qt-5/qsequentialanimationgroup.html#updateDirection',1,'QSequentialAnimationGroup::updateDirection()'],['https://doc.qt.io/qt-5/qparallelanimationgroup.html#updateDirection',1,'QParallelAnimationGroup::updateDirection()'],['https://doc.qt.io/qt-5/qabstractanimation.html#updateDirection',1,'QAbstractAnimation::updateDirection()']]],
  ['updateinterval_26',['updateInterval',['https://doc.qt.io/qt-5/qtimeline.html#updateInterval-prop',1,'QTimeLine::updateInterval()'],['https://doc.qt.io/qt-5/qtimeline.html#updateInterval-prop',1,'QTimeLine::updateInterval() const const']]],
  ['updatestate_27',['updateState',['https://doc.qt.io/qt-5/qabstractanimation.html#updateState',1,'QAbstractAnimation::updateState()'],['https://doc.qt.io/qt-5/qparallelanimationgroup.html#updateState',1,'QParallelAnimationGroup::updateState()'],['https://doc.qt.io/qt-5/qvariantanimation.html#updateState',1,'QVariantAnimation::updateState()'],['https://doc.qt.io/qt-5/qpropertyanimation.html#updateState',1,'QPropertyAnimation::updateState()'],['https://doc.qt.io/qt-5/qsequentialanimationgroup.html#updateState',1,'QSequentialAnimationGroup::updateState()']]],
  ['upperbound_28',['upperBound',['https://doc.qt.io/qt-5/qmap.html#upperBound',1,'QMap::upperBound(const Key &amp;key)'],['https://doc.qt.io/qt-5/qmap.html#upperBound-1',1,'QMap::upperBound(const Key &amp;key) const const']]],
  ['url_29',['url',['https://doc.qt.io/qt-5/qurl.html#url',1,'QUrl']]],
  ['urls_30',['urls',['https://doc.qt.io/qt-5/qmimedata.html#urls',1,'QMimeData']]],
  ['userinfo_31',['userInfo',['https://doc.qt.io/qt-5/qurl.html#userInfo',1,'QUrl']]],
  ['userinputresolutionoptions_32',['UserInputResolutionOptions',['https://doc.qt.io/qt-5/qurl.html#UserInputResolutionOption-enum',1,'QUrl']]],
  ['username_33',['userName',['https://doc.qt.io/qt-5/qurl.html#userName',1,'QUrl']]],
  ['userproperty_34',['userProperty',['https://doc.qt.io/qt-5/qmetaobject.html#userProperty',1,'QMetaObject']]],
  ['usertype_35',['userType',['https://doc.qt.io/qt-5/qvariant.html#userType',1,'QVariant::userType()'],['https://doc.qt.io/qt-5/qmetaproperty.html#userType',1,'QMetaProperty::userType()']]],
  ['usleep_36',['usleep',['https://doc.qt.io/qt-5/qthread.html#usleep',1,'QThread']]],
  ['utc_37',['utc',['https://doc.qt.io/qt-5/qtimezone.html#utc',1,'QTimeZone']]],
  ['utf16_38',['utf16',['https://doc.qt.io/qt-5/qstringview.html#utf16',1,'QStringView::utf16()'],['https://doc.qt.io/qt-5/qstring.html#utf16',1,'QString::utf16()']]],
  ['uuid_39',['uuid',['https://doc.qt.io/qt-5/qlowenergydescriptor.html#uuid',1,'QLowEnergyDescriptor::uuid()'],['https://doc.qt.io/qt-5/qlowenergycharacteristic.html#uuid',1,'QLowEnergyCharacteristic::uuid()'],['https://doc.qt.io/qt-5/qlowenergycharacteristicdata.html#uuid',1,'QLowEnergyCharacteristicData::uuid()'],['https://doc.qt.io/qt-5/qlowenergydescriptordata.html#uuid',1,'QLowEnergyDescriptorData::uuid()'],['https://doc.qt.io/qt-5/qlowenergyservicedata.html#uuid',1,'QLowEnergyServiceData::uuid()']]],
  ['uuidfilter_40',['uuidFilter',['https://doc.qt.io/qt-5/qbluetoothservicediscoveryagent.html#uuidFilter',1,'QBluetoothServiceDiscoveryAgent']]]
];
