Smithy Qt: Generator Class Reference
Generator Class Reference
Public Types
enum class ClobberMode { Prompt , Overwrite , Skip }
Public Member Functions
Generator (const smithy::Model *const model, Renderer *const renderer)
int expectedFileCount () const
bool generate (const QString &outputDir, ClobberMode clobberMode)
QStringList renderedFiles () const
QStringList skippedFiles () const
Protected Types
enum class Capitalisation {
NoChange = 0 , lowercase = 1 , camelCase = 2 , CamelCase = 3 ,
UPPERCASE = 4
}
Protected Member Functions
bool renderService (const smithy::Shape &service, const QStringList &templateNames, const QString &outputDir, ClobberMode &clobberMode)
bool renderOperation (const smithy::Shape &service, const smithy::Shape &operation, const QStringList &templateNames, const QString &outputDir, ClobberMode &clobberMode)
bool render (const QString &templateName, const QString &outputPathName, ClobberMode &clobberMode)
QVariantHash toContext (const smithy::Shape &shape) const
Static Protected Member Functions
static const QString canonicalServiceId (const QString &sdkId)
static bool promptToOverwrite (const QString &pathName, ClobberMode &clobberMode)
static Capitalisation getCase (const QString &first, const QString &second)
static QString makeCase (const QString &string, const Capitalisation &capitalisation)
static QString makeOutputPathName (const QString &templateName, const QRegularExpression &pattern, const QHash< QString, QString > &ids, const QString &outputDir=QString{})
static QStringList formatHtmlDocumentation (const QString &html)
Private Member Functions
Q_DECLARE_TR_FUNCTIONS (Generator)
Static Private Member Functions
static Q_LOGGING_CATEGORY (lc, "smithy.Generator", QtInfoMsg)
Logging category for Generator.
Private Attributes
const smithy::Model *const model
Renderer *const renderer
QStringList renderedPathNames
QStringList skippedPathNames
Static Private Attributes
static const QRegularExpression servicePattern
static const QRegularExpression operationPattern
Detailed Description
Definition at line 18 of file generator.h.
Member Enumeration Documentation
Capitalisation
enum class Generator::Capitalisation strong protected
Definition at line 39 of file generator.h.
{
        NoChange  = 0,
        lowercase = 1,
        camelCase = 2,
        CamelCase = 3,
        UPPERCASE = 4,
    };
ClobberMode
enum class Generator::ClobberMode strong
Definition at line 23 of file generator.h.
{
        Prompt,
        Overwrite,
        Skip,
    };
Constructor & Destructor Documentation
Generator()
Generator::Generator (const smithy::Model *const model, Renderer *const renderer)
Definition at line 43 of file generator.cpp.
    : model(model), renderer(renderer)
{
    Q_ASSERT(model->isValid());
    Q_ASSERT(renderer);
}
Member Function Documentation
canonicalServiceId()
const QString Generator::canonicalServiceId (const QString & sdkId) static protected
Definition at line 310 of file generator.cpp.
{
    // Handle some hard-coded special cases that are hard to automate without a dictionary.
    const QMap<QString,QString> specialCases{
        { QSL("identitystore"   ), QSL("IdentityStore")    },
        { QSL("ivschat"         ), QSL("IvsChat")          },
        { QSL("forecastquery"   ), QSL("ForecastQuery")    },
        { QSL("resiliencehub"   ), QSL("ResilienceHub")    },
        { QSL("savingsplans"    ), QSL("SavingsPlans")     },
        { QSL("codeartifact"    ), QSL("CodeArtifact")     },
        { QSL("imagebuilder"    ), QSL("ImageBuilder")     },
        { QSL("billingconductor"), QSL("BillingConductor") },
    };
    for (const auto iter = specialCases.constFind(sdkId); iter != specialCases.constEnd(); ) {
        return iter.value();
    }
    // Start with the sdkId.
    QString id = sdkId;
    // Convert runs of upercase letters with first-upper, and the rest lower.
    auto iter = QRegularExpression(QSL("[A-Z]{2,}([^a-zA-Z]|$)")).globalMatch(id);
    while (iter.hasNext()) {
        const auto match = iter.next();
        id.replace(match.capturedStart()+1, match.capturedLength()-1,
                   match.captured().mid(1).toLower());
    }
    // If the sdkId was all lowercase, then uppercase the first letter of each word.
    if (id.isLower()) {
        const QStringList words = id.split(QRegularExpression(QSL("[^a-zA-Z0-9]+")));
        id.clear();
        for (const QString &word: words) {
            id.append(word.at(0).toUpper() + word.mid(1));
        }
    }
    // Strip all non-alphanumeric characters, and any instances of "Amazon" and "AWS".
    id.replace(QRegularExpression(QSL("[^a-zA-Z0-9]|Amazon|AWS"),
               QRegularExpression::PatternOption::CaseInsensitiveOption),QString());
    // Remove any trailing instances of "API", "Client" and "Service".
    id.replace(QRegularExpression(QSL("(API|Client|Service)$"),
               QRegularExpression::PatternOption::CaseInsensitiveOption),QString());
    return id;
}
expectedFileCount()
int Generator::expectedFileCount () const
Definition at line 51 of file generator.cpp.
{
    const QHash<smithy::ShapeId, smithy::Shape> services = model->shapes(smithy::Shape::Type::Service);
    const int operations = std::accumulate(services.constBegin(), services.constEnd(), 0,
        [](const int a, const smithy::Shape &shape) { return a + shape.operations().size();
    });
    const QStringList templates = renderer->templatesNames();
    return std::accumulate(templates.constBegin(), templates.constEnd(), 0,
        [&](const int a, const QString &name) {
            return a + (servicePattern.match(name).hasMatch() ?
                (operationPattern.match(name).hasMatch() ? operations : services.size()) : 1);
        });
}
formatHtmlDocumentation()
QStringList Generator::formatHtmlDocumentation (const QString & html) static protected
Todo:
This is often dropping the last word of a sentence... won't fix yet so we can maintain the old aws-sdk-qt codegen behaviour until the swithover to smithy-qt templating is complete (ie to minimise the initial change-over diff).
Todo:
There's much more we can do here, indeed the documentation conversation still needs a lot of love. But its a start, and no point prioritising it yet, since its more important we get the code structure right first.
Definition at line 452 of file generator.cpp.
{
    QString content(html);
    /// @todo There's much more we can do here, indeed the documentation
    /// conversation still needs a lot of love. But its a start, and no point
    /// prioritising it yet, since its more important we get the code structure
    /// right first.
    content.replace(QSL("<function>"), QSL("<code>"));
    content.replace(QSL("</function>"), QSL("</code>"));
    content.replace(QSL("<important>"), QSL("<b>"));
    content.replace(QSL("</important>"), QSL("</b>"));
    // Replace /* and */ with &ast; versions to avoid breaking comment blocks.
    content.replace(QSL("/*"), QSL("/&ast;"));
    content.replace(QSL("*/"), QSL("&ast;/"));
    QStringList lines;
    QString line;
    #if (QT_VERSION > QT_VERSION_CHECK(5, 14, 0))
        #define SKIP_EMPTY_PARTS Qt::SkipEmptyParts // Introduced in Qt 5.14.
    #else
        #define SKIP_EMPTY_PARTS QString::SkipEmptyParts // Deprecated in Qt 5.15.
    #endif
    foreach (QString word, content.split(QRegularExpression(QSL("\\s+")), SKIP_EMPTY_PARTS)) {
        if (word.startsWith(QSL("<p>")) || word.endsWith(QSL("</p>"))) {
            lines.append(line);
            line.clear();
            if (!lines.last().isEmpty()) {
                lines.append(QString()); // A blank line.
            }
            if (word.startsWith(QSL("<p>"))) {
                word.remove(0,3);
            }
            if (word.endsWith(QSL("</p>"))) {
                word.remove(word.size()-5,4);
            }
        }
        if (line.isEmpty()) {
            line += word;
        } else if (line.size() + word.size() < 120) {
            line += QLatin1Char(' ') + word;
        } else {
            lines.append(line);
            line = word;
        }
    }
    // Remove leading and trailing blank lines.
    while ((!lines.isEmpty()) && (lines.first().isEmpty())) {
        lines.removeFirst();
    }
    while ((!lines.isEmpty()) && (lines.last().isEmpty())) {
        lines.removeLast();
    }
    return lines;
}
References QList::append(), QString::clear(), QString::endsWith(), QList::first(), QString::isEmpty(), QList::isEmpty(), QList::last(), QString::remove(), QList::removeFirst(), QList::removeLast(), QString::replace(), QString::size(), QString::split(), and QString::startsWith().
generate()
bool Generator::generate (const QString & outputDir, ClobberMode clobberMode)
Todo:
Make this QVariantHash servicesMap instead of QJsonObject, and use toContext().
Definition at line 65 of file generator.cpp.
{
    // Add initial context.
    /// \todo Make this QVariantHash servicesMap instead of QJsonObject, and use toContext().
    QVariantMap servicesMap;
    const QHash<smithy::ShapeId, smithy::Shape> services = model->shapes(smithy::Shape::Type::Service);
    for (const smithy::Shape &service: services) {
        servicesMap.insert(service.id().toString(), toContext(service));
    }
    const ScopedContext context(renderer, { { QSL("services"), servicesMap } });
    // Build the list of template names.
    const QStringList templatesNames = renderer->templatesNames();
    QStringList serviceTemplateNames, operationTemplateNames, plainTemplateNames;
    for (const QString &name: templatesNames) {
        ((servicePattern.match(name).hasMatch()) ? (operationPattern.match(name).hasMatch() ?
            operationTemplateNames : serviceTemplateNames) : plainTemplateNames).append(name);
    }
    Q_ASSERT(serviceTemplateNames.size() + operationTemplateNames.size()
             + plainTemplateNames.size() == templatesNames.size());
    // Render all of the services.
    for (const smithy::Shape &service: services) {
        if (!renderService(service, serviceTemplateNames, outputDir, clobberMode)) {
            return false;
        }
        const smithy::Shape::ShapeReferences operations = service.operations();
        for (const smithy::Shape::ShapeReference &shapeRef: operations) {
            const smithy::Shape operation = model->shape(shapeRef.target);
            if (!operation.isValid()) {
                qCCritical(lc).noquote() << tr("Failed to find shape for %1 operation in %2 service")
                    .arg(shapeRef.target.toString(), service.id().toString());
                return false;
            }
            if (!renderOperation(service, operation, operationTemplateNames, outputDir,
                                 clobberMode)) {
                return false;
            }
        }
    }
    // Render all of the one-off (not per-service) files.
    qCDebug(lc).noquote() << tr("Rendering %n unary template/s", nullptr, plainTemplateNames.size());
    return std::all_of(plainTemplateNames.constBegin(), plainTemplateNames.constEnd(),
        [&](const QString &templateName){
            const QString outputPathName = outputDir + QLatin1Char('/') + templateName;
            return render(templateName, outputPathName, clobberMode);
    });
}
References QList::append(), QList::constBegin(), QList::constEnd(), QRegularExpressionMatch::hasMatch(), QRegularExpression::match(), and QList::size().
getCase()
Generator::Capitalisation Generator::getCase (const QString & first, const QString & second) static protected
Definition at line 388 of file generator.cpp.
{
    if (first.isLower() && second.isLower()) {
        return Capitalisation::lowercase;
    }
    if (first.isUpper() && second.isUpper()) {
        return Capitalisation::UPPERCASE;
    }
    if (first.front().isLower() && second.front().isUpper()) {
        return Capitalisation::camelCase;
    }
    if (first.front().isUpper() && second.front().isUpper()) {
        return Capitalisation::CamelCase;
    }
    return Capitalisation::NoChange;
}
makeCase()
QString Generator::makeCase (const QString & string, const Capitalisation & capitalisation) static protected
Definition at line 405 of file generator.cpp.
{
    switch (capitalisation) {
    case Capitalisation::NoChange:
        return string;
    case Capitalisation::lowercase:
        return string.toLower();
    case Capitalisation::camelCase:
        Q_UNIMPLEMENTED();
        break;
    case Capitalisation::CamelCase:
        Q_UNIMPLEMENTED();
        break;
    case Capitalisation::UPPERCASE:
        return string.toUpper();
    }
    qCCritical(lc).noquote() << tr("Unknown capitalisation %1 for %2")
        .arg((int)capitalisation).arg(string);
    return QString{};
}
makeOutputPathName()
QString Generator::makeOutputPathName (const QString & templateName, const QRegularExpression & pattern, const QHash< QString, QString > & ids, const QString & outputDir = QString{}) static protected
Definition at line 426 of file generator.cpp.
{
    QString outputPathName = templateName;
    for (auto iter = pattern.globalMatch(templateName); iter.hasNext(); ) {
        const QRegularExpressionMatch match = iter.next();
        const QString type = match.captured(QSL("type"));
        const QString sep = match.captured(QSL("separator"));
        const QString id = match.captured(QSL("id"));
        const QString newId = ids.value(id.toLower());
        if (newId.isNull()) {
            qCCritical(lc).noquote() << tr("No pathname ID value for %1").arg(id);
            return QString{};
        }
        const QString label = makeCase(newId, getCase(type, id)).replace(QLatin1Char(' '), sep);
        outputPathName.replace(type+sep+id, label);
    }
    if (!outputDir.isEmpty()) {
        outputPathName.prepend(outputDir + QLatin1Char('/'));
    }
    return outputPathName;
}
promptToOverwrite()
bool Generator::promptToOverwrite (const QString & pathName, ClobberMode & clobberMode) static protected
Definition at line 357 of file generator.cpp.
{
    Q_ASSERT(clobberMode == ClobberMode::Prompt);
    while (true) {
        qCWarning(lc).noquote() << tr("Overwrite %1 [y,n,a,s,q,?]? ").arg(pathName);
        QTextStream stream(stdin);
        const QString response = stream.readLine().toLower();
        if (response == QSL("y")) {
            return true;
        } else if (response == QSL("n")) {
            return false;
        } else if (response == QSL("a")) {
            clobberMode = ClobberMode::Overwrite;
            return true;
        } else if (response == QSL("s")) {
            clobberMode = ClobberMode::Skip;
            return false;
        } else if (response == QSL("q")) {
            QCoreApplication::exit(EXIT_FAILURE);
        } else {
            qCInfo(lc).noquote() << tr("y - overwrite this file");
            qCInfo(lc).noquote() << tr("n - do not overwrite this file");
            qCInfo(lc).noquote() << tr("a - overwrite this, and all remaining files");
            qCInfo(lc).noquote() << tr("s - do not overwrite this, or any remaining files");
            qCInfo(lc).noquote() << tr("q - quit now, without writing any further files");
            qCInfo(lc).noquote() << tr("? - print help");
        }
    }
    Q_UNREACHABLE();
}
render()
bool Generator::render (const QString & templateName, const QString & outputPathName, ClobberMode & clobberMode) protected
Definition at line 193 of file generator.cpp.
{
    if (QFile::exists(outputPathName)) {
        switch (clobberMode) {
        case ClobberMode::Overwrite:
            qCDebug(lc) << tr("Overwriting existing file: %1").arg(outputPathName);
            break;
        case ClobberMode::Prompt:
            if (promptToOverwrite(outputPathName, clobberMode)) {
                break; // User said yes, so jump out of case statement.
            }
            __attribute__((fallthrough));
        case ClobberMode::Skip:
            qCDebug(lc) << tr("Skipping existing output file: %1").arg(outputPathName);
            skippedPathNames.append(outputPathName);
            return true;
        }
    }
    if (!renderer->render(templateName, outputPathName)) {
        return false;
    }
    renderedPathNames.append(outputPathName);
    return true;
}
renderedFiles()
QStringList Generator::renderedFiles () const
Definition at line 115 of file generator.cpp.
{
    return renderedPathNames;
}
renderOperation()
bool Generator::renderOperation (const smithy::Shape & service, const smithy::Shape & operation, const QStringList & templateNames, const QString & outputDir, ClobberMode & clobberMode) protected
Definition at line 157 of file generator.cpp.
{
    qCDebug(lc).noquote() << tr("Rendering templates for operation %1").arg(operation.id().toString());
    // Add renderer context for this operation.
    // cppcheck-suppress unreadVariable
    const ScopedContext context(renderer, { { QSL("operation"), toContext(operation) } });
    const QString apiTitle = service.traits().value(QSL("smithy.api#title")).toString();
    const QString sdkId = service.traits().value(QSL("aws.api#service")).toObject().value(QSL("sdkId")).toString();
    if (apiTitle.isEmpty()) {
        qCCritical(lc).noquote() << tr("Service %1 has no API title").arg(service.id().toString());
        return false;
    }
    if (sdkId.isEmpty()) {
        qCCritical(lc).noquote() << tr("Service %1 has no SDK ID").arg(service.id().toString());
        return false;
    }
    for (const QString &templateName: templateNames) {
        QString outputPathName = makeOutputPathName(templateName, servicePattern, {
            { QSL("name"), apiTitle },
            { QSL("sdkid"), sdkId },
        });
        outputPathName = makeOutputPathName(outputPathName, operationPattern, {
            { QSL("name"), operation.id().shapeName() },
        }, outputDir);
        if (!render(templateName, outputPathName, clobberMode)) {
            return false;
        }
    }
    return true;
}
renderService()
bool Generator::renderService (const smithy::Shape & service, const QStringList & templateNames, const QString & outputDir, ClobberMode & clobberMode) protected
Definition at line 125 of file generator.cpp.
{
    qCDebug(lc).noquote() << tr("Rendering templates for service %1").arg(service.id().toString());
    // Add renderer context for this service.
    // cppcheck-suppress unreadVariable
    const ScopedContext context(renderer, { { QSL("service"), toContext(service) } });
    // Render each service template.
    const QString apiTitle = service.traits().value(QSL("smithy.api#title")).toString();
    if (apiTitle.isEmpty()) {
        qCCritical(lc).noquote() << tr("Service %1 has no API title").arg(service.id().toString());
        return false;
    }
    const QString sdkId = service.traits().value(QSL("aws.api#service")).toObject().value(QSL("sdkId")).toString();
    if (sdkId.isEmpty()) {
        qCCritical(lc).noquote() << tr("Service %1 has no SDK ID").arg(service.id().toString());
        return false;
    }
    for (const QString &templateName: templateNames) {
        const QString outputPathName = makeOutputPathName(templateName, servicePattern, {
            { QSL("name"), apiTitle },
            { QSL("sdkid"), sdkId },
        }, outputDir);
        if (!render(templateName, outputPathName, clobberMode)) {
            return false;
        }
    }
    return true;
}
skippedFiles()
QStringList Generator::skippedFiles () const
Definition at line 120 of file generator.cpp.
{
    return skippedPathNames;
}
toContext()
QVariantHash Generator::toContext (const smithy::Shape & shape) const protected
Definition at line 220 of file generator.cpp.
{
    if (shape.type() == smithy::Shape::Type::Service) {
        QVariantHash hash = shape.rawAst().toVariantHash();
        hash.insert(QSL("canonicalId"), canonicalServiceId(shape.traits()
            .value(QSL("aws.api#service")).toObject().value(QSL("sdkId")).toString()));
        hash.insert(QSL("sdkId"), shape.traits().value(QSL("aws.api#service")).toObject()
            .value(QSL("sdkId")).toString());
        hash.insert(QSL("documentation"), formatHtmlDocumentation(
            shape.traits().value(QSL("smithy.api#documentation")).toString()));
        QVariantMap operations;
        const smithy::Shape::ShapeReferences operationRefs = shape.operations();
        for (const smithy::Shape::ShapeReference &operationRef: operationRefs) {
            operations.insert(operationRef.target.shapeName(),
                              toContext(model->shape(operationRef.target)));
        }
        Q_ASSERT(operationRefs.size() == operations.size());
        const smithy::Shape::ShapeReferences resourceRefs = shape.resources();
        for (const smithy::Shape::ShapeReference &resourceRef: resourceRefs) {
            const QVariantHash resourceContext = toContext(model->shape(resourceRef.target));
            // resourceContext will contain the raw AST, and probably other things too over time,
            // but for now (to replicate historical aws-sdk-qt codegen behaviour) we just want to
            // add the resource operations to the service operations list.
            const QVariantMap resourceOperations = resourceContext.value(QSL("operations")).toMap();
            for (auto iter = resourceOperations.constBegin(); iter != resourceOperations.constEnd(); ++iter) {
                operations.insert(iter.key(), iter.value());
            }
        }
        hash.insert(QSL("operations"), operations);
        return hash;
    }
    if (shape.type() == smithy::Shape::Type::Operation) {
        QVariantHash hash = shape.rawAst().toVariantHash();
        hash.insert(QSL("name"), shape.id().shapeName());
        hash.insert(QSL("documentation"), formatHtmlDocumentation(
            shape.traits().value(QSL("smithy.api#documentation")).toString()));
        return hash;
    }
    if (shape.type() == smithy::Shape::Type::Resource) {
        QVariantHash hash = shape.rawAst().toVariantHash();
        QVariantMap operations;
        #define QTSMITHY_IF_VALID_INSERT(action) { \
            const smithy::ShapeId action##TargetId = shape.action().target; \
            if (action##TargetId.isValid()) {                   \
                operations.insert(action##TargetId.shapeName(), \
                    toContext(model->shape(action##TargetId))); \
            } \
        }
        QTSMITHY_IF_VALID_INSERT(create)
        QTSMITHY_IF_VALID_INSERT(put)
        QTSMITHY_IF_VALID_INSERT(read)
        QTSMITHY_IF_VALID_INSERT(update)
        QTSMITHY_IF_VALID_INSERT(Delete)
        QTSMITHY_IF_VALID_INSERT(list)
        #undef QTSMITHY_IF_VALID_INSERT
        #define QTSMITHY_ADD_SHAPES(property) { \
            const smithy::Shape::ShapeReferences refs = shape.property(); \
            for (const smithy::Shape::ShapeReference &ref: refs) { \
                operations.insert(ref.target.shapeName(), toContext(model->shape(ref.target))); \
            } \
        }
        QTSMITHY_ADD_SHAPES(operations)
        QTSMITHY_ADD_SHAPES(collectionOperations)
        #undef QTSMITHY_ADD_SHAPES
        const smithy::Shape::ShapeReferences resourceRefs = shape.resources();
        for (const smithy::Shape::ShapeReference &resourceRef: resourceRefs) {
            const QVariantHash resourceContext = toContext(model->shape(resourceRef.target));
            // resourceContext will contain the raw AST, and probably other things too over time,
            // but for now (to replicate historical aws-sdk-qt codegen behaviour) we just want to
            // add the resource operations to the service operations list.
            const QVariantMap resourceOperations = resourceContext.value(QSL("operations")).toMap();
            for (auto iter = resourceOperations.constBegin(); iter != resourceOperations.constEnd(); ++iter) {
                operations.insert(iter.key(), iter.value());
            }
        }
        hash.insert(QSL("operations"), operations);
        return hash;
    }
    qCCritical(lc).noquote() << tr("Cannot generate context for shape type 0x%1")
        .arg((int)shape.type(), 0, 16);
    return QVariantHash{};
}
Member Data Documentation
model
const smithy::Model* const Generator::model private
Definition at line 72 of file generator.h.
operationPattern
const QRegularExpression Generator::operationPattern static private
Initial value:
{
    QSL("(?<type>Operation)(?<seperator>[^a-zA-Z0-9]*)(?<id>Name)"),
    QRegularExpression::CaseInsensitiveOption
}
Definition at line 78 of file generator.h.
renderedPathNames
QStringList Generator::renderedPathNames private
Definition at line 74 of file generator.h.
renderer
Renderer* const Generator::renderer private
Definition at line 73 of file generator.h.
servicePattern
const QRegularExpression Generator::servicePattern static private
Initial value:
{
    QSL("(?<type>Service)(?<seperator>[^a-zA-Z0-9]*)(?<id>Title|sdkId)"),
    QRegularExpression::CaseInsensitiveOption
}
Definition at line 77 of file generator.h.
skippedPathNames
QStringList Generator::skippedPathNames private
Definition at line 75 of file generator.h.
The documentation for this class was generated from the following files:
generator.h
generator.cpp