Smithy Qt: ShapeId Class Reference
ShapeId Class Reference
The ShapeId class provides a Qt representation of a Smithy Shape ID.
Public Member Functions
ShapeId ()
Constructs an empty ShapeId object.
ShapeId (ShapeId &&other)
Constructs a ShapeId object by moving resources from other.
ShapeId (const ShapeId &other)
Constructs a ShapeId object by copying other.
ShapeId (const QString &shapeId)
Constructs a ShapeId object by parsing the Smithy Shape ID given by shapeId.
ShapeId & operator= (const ShapeId &shapeId)
Assigns the specified shapeId to this object.
ShapeId & operator= (const ShapeId &&shapeId)
Moves the specified shapeId to this object.
ShapeId & operator= (const QString &shapeId)
Assigns the specified shapeId to this object.
~ShapeId ()
Destroys this ShapeId object.
QString memberName () const
Returns the Shape ID's member name, if it has one, otherwise a null string.
QString nameSpace () const
Returns the Shape ID's namespace, if it has one, otherwise a null string.
QString shapeName () const
Returns the Shape ID's shape name, if it has one, otherwise a null string.
void setMemberName (const QString &name)
Set the Shape ID's member name to name, which may be an empty or null string.
void setNameSpace (const QString &name)
Set the Shape ID's namespace to name, which may be an empty or null string.
void setShapeName (const QString &name)
Set the Shape ID's shape name to name.
QString absoluteShapeId () const
Returns this object as an absolute Smithy Shape ID if this object has a namespace, otherwise a null string.
QString relativeShapeId () const
Returns this object as a relative Smithy Shape ID, that one without a leading namespace.
QString toString () const
Returns this object as an absolute Smithy Shape ID if this object has a namespace, otherwise a relative Smithy Shape ID.
bool hasNameSpace () const
Returns true if this Shape ID has a non-empty namespace, otherwise false otherwise.
bool hasMemberName () const
Returns true if this Shape ID has a non-empty member name, otherwise false otherwise.
bool isAbsoluteRootShapeId () const
Returns true if this Shape ID is a root Shape ID, and has a namespace, false otherwise.
bool isRootShapeId () const
Returns true if this Shape ID is a root Shape ID, false otherwise.
bool isRelativeShapeId () const
Returns true if this Shape ID is a relative Shape ID, false otherwise.
bool isValid () const
Returns true if this object represents a valid, non-empty Smithy Shape ID.
bool operator== (const ShapeId &other) const
Private Member Functions
Q_DECLARE_TR_FUNCTIONS (ShapeId)
Private Attributes
ShapeIdPrivate * d_ptr
Detailed Description
The ShapeId class provides a Qt representation of a Smithy Shape ID.
See also
https://awslabs.github.io/smithy/2.0/spec/model.html#shape-id
Definition at line 23 of file shapeid.h.
Constructor & Destructor Documentation
ShapeId() [1/4]
ShapeId::ShapeId ()
Constructs an empty ShapeId object.
Definition at line 27 of file shapeid.cpp.
                 : d_ptr(new ShapeIdPrivate(this))
{
}
References d_ptr.
Referenced by isValid(), memberName(), nameSpace(), operator=(), operator=(), operator=(), setMemberName(), setNameSpace(), setShapeName(), ShapeId(), ShapeId(), ShapeId(), and shapeName().
ShapeId() [2/4]
ShapeId::ShapeId (ShapeId && other)
Constructs a ShapeId object by moving resources from other.
Definition at line 35 of file shapeid.cpp.
                                : d_ptr(new ShapeIdPrivate(this))
{
    Q_D(ShapeId);
    d->memberName = std::move(other.d_ptr->memberName);
    d->nameSpace = std::move(other.d_ptr->nameSpace);
    d->shapeName = std::move(other.d_ptr->shapeName);
}
References d_ptr, and ShapeId().
ShapeId() [3/4]
ShapeId::ShapeId (const ShapeId & other)
Constructs a ShapeId object by copying other.
Definition at line 46 of file shapeid.cpp.
                                     : d_ptr(new ShapeIdPrivate(this))
{
    Q_D(ShapeId);
    d->memberName = other.d_ptr->memberName;
    d->nameSpace = other.d_ptr->nameSpace;
    d->shapeName = other.d_ptr->shapeName;
}
References d_ptr, and ShapeId().
ShapeId() [4/4]
ShapeId::ShapeId (const QString & shapeId)
Constructs a ShapeId object by parsing the Smithy Shape ID given by shapeId.
To be considered valid, shapeId must contain at least a valid shape name, but may also contain optional namespace and member name components. Use isValid() to verify shapeId's validity.
See also
isValid
https://awslabs.github.io/smithy/2.0/spec/model.html#shape-id
Definition at line 63 of file shapeid.cpp.
                                       : d_ptr(new ShapeIdPrivate(this))
{
    Q_D(ShapeId);
    d->setShapeId(shapeId);
}
References d_ptr, and ShapeId().
~ShapeId()
ShapeId::~ShapeId ()
Destroys this ShapeId object.
Definition at line 106 of file shapeid.cpp.
{
    delete d_ptr;
}
References d_ptr.
Member Function Documentation
absoluteShapeId()
QString ShapeId::absoluteShapeId () const
Returns this object as an absolute Smithy Shape ID if this object has a namespace, otherwise a null string.
Note
, Smithy defines an absolute Shape ID as one that begins with a namespace, therefore it is not possible to return an absolute Shape ID if no namespace has been set.
, if the Shape ID is invalid (ie isValid() returns false) it still safe to invoke this method, but the result is undefined.
See also
setNameSpace
isValid
Definition at line 185 of file shapeid.cpp.
{
    return hasNameSpace() ? QStringLiteral("%1#%2").arg(nameSpace(), relativeShapeId()) : QString();
}
References hasNameSpace(), nameSpace(), and relativeShapeId().
Referenced by toString().
hasMemberName()
bool ShapeId::hasMemberName () const
Returns true if this Shape ID has a non-empty member name, otherwise false otherwise.
See also
memberName.
setMemberName.
Definition at line 236 of file shapeid.cpp.
{
    return !memberName().isEmpty();
}
References memberName().
Referenced by isRootShapeId(), and relativeShapeId().
hasNameSpace()
bool ShapeId::hasNameSpace () const
Returns true if this Shape ID has a non-empty namespace, otherwise false otherwise.
See also
nameSpace.
setNameSpace.
Definition at line 225 of file shapeid.cpp.
{
    return !nameSpace().isEmpty();
}
References nameSpace().
Referenced by absoluteShapeId(), Model::insert(), isAbsoluteRootShapeId(), isRelativeShapeId(), and toString().
isAbsoluteRootShapeId()
bool ShapeId::isAbsoluteRootShapeId () const
Returns true if this Shape ID is a root Shape ID, and has a namespace, false otherwise.
See also
isRootShapeId.
hasNameSpace.
Definition at line 247 of file shapeid.cpp.
{
    return isRootShapeId() && hasNameSpace();
}
References hasNameSpace(), and isRootShapeId().
isRelativeShapeId()
bool ShapeId::isRelativeShapeId () const
Returns true if this Shape ID is a relative Shape ID, false otherwise.
Note
, Smithy defines a relative Shape ID as one that does not have a namespace.
See also
hasNameSpace.
Definition at line 271 of file shapeid.cpp.
{
    return !hasNameSpace();
}
References hasNameSpace().
isRootShapeId()
bool ShapeId::isRootShapeId () const
Returns true if this Shape ID is a root Shape ID, false otherwise.
Note
, Smithy defines a root Shape ID as one that does not have a member name.
See also
hasMemberName.
Definition at line 259 of file shapeid.cpp.
{
    return !hasMemberName();
}
References hasMemberName().
Referenced by isAbsoluteRootShapeId().
isValid()
bool ShapeId::isValid () const
Returns true if this object represents a valid, non-empty Smithy Shape ID.
See also
https://awslabs.github.io/smithy/2.0/spec/model.html#shape-id
Definition at line 281 of file shapeid.cpp.
{
    Q_D(const ShapeId);
    // Validate the (optional) namespace.
    if (!d->nameSpace.isEmpty()) {
        static QRegularExpression namespacePattern(QStringLiteral("^(_*[a-zA-Z]\\w*\\.?)+(?<!\\.)$"));
        Q_ASSERT(namespacePattern.isValid());
        if (!namespacePattern.match(d->nameSpace).hasMatch()) {
            return false;
        }
    }
    // Validate the (required) shape name.
    static QRegularExpression identifierPattern(QStringLiteral("^_*[a-zA-Z]\\w*$"));
    Q_ASSERT(identifierPattern.isValid());
    if ((d->shapeName.isEmpty()) || (!identifierPattern.match(d->shapeName).hasMatch())) {
        return false;
    }
    // Validate the (optional) member name.
    if ((!d->memberName.isEmpty()) && (!identifierPattern.match(d->memberName).hasMatch())) {
        return false;
    }
    return true; // Valid.
}
References ShapeId().
Referenced by Model::insert().
memberName()
QString ShapeId::memberName () const
Returns the Shape ID's member name, if it has one, otherwise a null string.
Definition at line 114 of file shapeid.cpp.
{
    Q_D(const ShapeId);
    return d->memberName;
}
References ShapeId().
Referenced by hasMemberName(), and relativeShapeId().
nameSpace()
QString ShapeId::nameSpace () const
Returns the Shape ID's namespace, if it has one, otherwise a null string.
Definition at line 123 of file shapeid.cpp.
{
    Q_D(const ShapeId);
    return d->nameSpace;
}
References ShapeId().
Referenced by absoluteShapeId(), and hasNameSpace().
operator=() [1/3]
ShapeId & ShapeId::operator= (const QString & shapeId)
Assigns the specified shapeId to this object.
Definition at line 96 of file shapeid.cpp.
{
    Q_D(ShapeId);
    d->setShapeId(shapeId);
    return *this;
}
References ShapeId().
operator=() [2/3]
ShapeId & ShapeId::operator= (const ShapeId && shapeId)
Moves the specified shapeId to this object.
Definition at line 84 of file shapeid.cpp.
{
    Q_D(ShapeId);
    d->memberName = std::move(shapeId.d_ptr->memberName);
    d->nameSpace = std::move(shapeId.d_ptr->nameSpace);
    d->shapeName = std::move(shapeId.d_ptr->shapeName);
    return *this;
}
References ShapeId().
operator=() [3/3]
ShapeId & ShapeId::operator= (const ShapeId & shapeId)
Assigns the specified shapeId to this object.
Definition at line 72 of file shapeid.cpp.
{
    Q_D(ShapeId);
    d->memberName = shapeId.d_ptr->memberName;
    d->nameSpace = shapeId.d_ptr->nameSpace;
    d->shapeName = shapeId.d_ptr->shapeName;
    return *this;
}
References d_ptr, and ShapeId().
operator==()
bool ShapeId::operator== (const ShapeId & other) const
Definition at line 307 of file shapeid.cpp.
{
    Q_D(const ShapeId);
    return (d->memberName == other.d_ptr->memberName) &&
           (d->nameSpace == other.d_ptr->nameSpace)   &&
           (d->shapeName == other.d_ptr->shapeName);
}
relativeShapeId()
QString ShapeId::relativeShapeId () const
Returns this object as a relative Smithy Shape ID, that one without a leading namespace.
Note
, if the Shape ID is invalid (ie isValid() returns false) it still safe to invoke this method, but the result is undefined.
See also
isValid
Definition at line 198 of file shapeid.cpp.
{
    return hasMemberName() ? QStringLiteral("%1$%2").arg(shapeName(), memberName()) : shapeName();
}
References hasMemberName(), memberName(), and shapeName().
Referenced by absoluteShapeId(), and toString().
setMemberName()
void ShapeId::setMemberName (const QString & name)
Set the Shape ID's member name to name, which may be an empty or null string.
Definition at line 145 of file shapeid.cpp.
{
    Q_D(ShapeId);
    d->memberName = name;
}
References ShapeId().
setNameSpace()
void ShapeId::setNameSpace (const QString & name)
Set the Shape ID's namespace to name, which may be an empty or null string.
Definition at line 154 of file shapeid.cpp.
{
    Q_D(ShapeId);
    d->nameSpace = name;
}
References ShapeId().
setShapeName()
void ShapeId::setShapeName (const QString & name)
Set the Shape ID's shape name to name.
Note, a Shape ID is considered invalid if it has no shape name, so name should typically be non-empty.
Definition at line 166 of file shapeid.cpp.
{
    Q_D(ShapeId);
    d->shapeName = name;
}
References ShapeId().
shapeName()
QString ShapeId::shapeName () const
Returns the Shape ID's shape name, if it has one, otherwise a null string.
Note, a Shape ID is considered invalid if it has no shape name.
See also
isValid
Definition at line 136 of file shapeid.cpp.
{
    Q_D(const ShapeId);
    return d->shapeName;
}
References ShapeId().
Referenced by relativeShapeId().
toString()
QString ShapeId::toString () const
Returns this object as an absolute Smithy Shape ID if this object has a namespace, otherwise a relative Smithy Shape ID.
Note
, if the Shape ID is invalid (ie isValid() returns false) it still safe to invoke this method, but the result is undefined.
See also
absoluteShapeId
relativeShapeId
isValid
Definition at line 214 of file shapeid.cpp.
{
    return hasNameSpace() ? absoluteShapeId() : relativeShapeId();
}
References absoluteShapeId(), hasNameSpace(), and relativeShapeId().
Referenced by Model::insert().
Member Data Documentation
d_ptr
ShapeIdPrivate* ShapeId::d_ptr private
Internal d-pointer.
Definition at line 60 of file shapeid.h.
Referenced by operator=(), ShapeId(), ShapeId(), ShapeId(), ShapeId(), and ~ShapeId().
The documentation for this class was generated from the following files:
shapeid.h
shapeid.cpp