Smithy Qt: Model Class Reference
Model Class Reference
The Model class provides a Qt representation of a Smithy semantic model.
Public Types
enum class Error {
NoError = 0 , NoData = 1 , InvalidMetadata = 2 , InvalidShapes = 3 ,
InvalidShapeId = 4 , InvalidShape = 5 , ConflictingMetadata = 6
}
Public Member Functions
Model ()
Constructs a new, empty Smithy model.
Model (Model &&other)
Model (const Model &other)
Model & operator= (const Model &model)
Model & operator= (const Model &&model)
~Model ()
Destroys this Model object.
void clear ()
bool insert (const QJsonObject &ast)
Add the logical content of the JSON AST model file given by ast into this semantic model.
bool finish ()
Error error () const
bool isValid () const
QJsonObject metadata () const
QHash< ShapeId, Shape > shapes (const Shape::Type &type=Shape::Type::Undefined) const
Protected Attributes
ModelPrivate * d_ptr
Private Member Functions
Q_DECLARE_TR_FUNCTIONS (Model)
Detailed Description
The Model class provides a Qt representation of a Smithy semantic model.
See also
https://awslabs.github.io/smithy/2.0/spec/model.html#semantic-model
Definition at line 26 of file model.h.
Member Enumeration Documentation
Error
enum class Model::Error strong
Definition at line 31 of file model.h.
                     {
        NoError             = 0,
        NoData              = 1,
        InvalidMetadata     = 2,
        InvalidShapes       = 3,
        InvalidShapeId      = 4,
        InvalidShape        = 5,
        ConflictingMetadata = 6,
    };
Constructor & Destructor Documentation
Model() [1/3]
Model::Model ()
Constructs a new, empty Smithy model.
Todo:
Load the Smithy prelude here?
Definition at line 27 of file model.cpp.
             : d_ptr(new ModelPrivate(this))
{
    Q_D(Model);
    d->error = Error::NoData;
    /// \todo Load the Smithy prelude here?
}
Model() [2/3]
Model::Model (Model && other)
Definition at line 34 of file model.cpp.
                          : d_ptr(new ModelPrivate(this))
{
    Q_D(Model);
    d->error = std::move(other.d_ptr->error);
    d->mergedMetadata = std::move(other.d_ptr->mergedMetadata);
    d->mergedShapes = std::move(other.d_ptr->mergedShapes);
    d->allMetadata = std::move(other.d_ptr->allMetadata);
    d->allShapes = std::move(other.d_ptr->allShapes);
}
Model() [3/3]
Model::Model (const Model & other)
Definition at line 44 of file model.cpp.
                               : d_ptr(new ModelPrivate(this))
{
    Q_D(Model);
    d->error = other.d_ptr->error;
    d->mergedMetadata = other.d_ptr->mergedMetadata;
    d->mergedShapes = other.d_ptr->mergedShapes;
    d->allMetadata = other.d_ptr->allMetadata;
    d->allShapes = other.d_ptr->allShapes;
}
~Model()
Model::~Model ()
Destroys this Model object.
Definition at line 79 of file model.cpp.
{
    delete d_ptr;
}
References d_ptr.
Member Function Documentation
clear()
void Model::clear ()
Definition at line 84 of file model.cpp.
{
    Q_D(Model);
    d->error = Error::NoData;
    d->mergedMetadata = QJsonObject{};
    d->mergedShapes.clear();
    d->allMetadata.clear();
    d->allShapes.clear();
}
error()
Model::Error Model::error () const
Definition at line 205 of file model.cpp.
{
    Q_D(const Model);
    return d->error;
}
finish()
bool Model::finish ()
Todo:
resolve shape conflicts.
Todo:
Todo:
resolve trait conflicts; include 'apply' statements.
Definition at line 186 of file model.cpp.
{
    Q_D(Model);
    if (d->error != Error::NoError) {
        qCWarning(d->lc).noquote() << tr("Model::finish() called with Model errors present");
        return false;
    }
    d->mergedMetadata = ModelPrivate::mergeMetadata(d->allMetadata);
    if (d->allMetadata.isEmpty() != d->mergedMetadata.isEmpty()) {
        if (d->error == Error::NoError) d->error = Error::ConflictingMetadata;
    }
    /// \todo resolve shape conflicts.
    /// \todo resolve trait conflicts; include 'apply' statements.
    Q_UNIMPLEMENTED();
    return isValid();
}
insert()
bool Model::insert (const QJsonObject & ast)
Add the logical content of the JSON AST model file given by ast into this semantic model.
A Smithy semantic model is split into one or more model files. Use this method to add all model files that comprise this semantic model.
See also
https://awslabs.github.io/smithy/2.0/spec/model.html
Definition at line 102 of file model.cpp.
{
    Q_D(Model);
    if (d->error == Error::NoData) {
        d->error = Error::NoError;
    }
    // Clear any previously-merged data; we'll need to re-merge later.
    d->mergedMetadata = QJsonObject{};
    d->mergedShapes.clear();
    // Fetch the Smithy version.
    const QVersionNumber version = d->smithyVersion(ast);
    if (version.majorVersion() > 2) {
        qCWarning(d->lc).noquote() << tr("Unknown Smithy version %1").arg(version.toString());
    }
    // Warn on any unrecognised top-level Smithy AST properties.
    // https://awslabs.github.io/smithy/2.0/spec/json-ast.html#top-level-properties
    const QStringList keys = ast.keys();
    for (const QString &key: keys) {
        const QStringList knownKeys{
            QStringLiteral("smithy"),QStringLiteral("metadata"), QStringLiteral("shapes") };
        if (!knownKeys.contains(key)) {
            qCWarning(d->lc).noquote() << tr("Ignoring unknown Smithy AST property %1").arg(key);
        }
    }
    // Process the (optional) metadata.
    const QJsonValue metadata = ast.value(QStringLiteral("metadata"));
    if (metadata != QJsonValue::Undefined) {
        if (!metadata.isObject()) {
            qCCritical(d->lc).noquote() << tr("Smithy AST metadata is not an object");
            qDebug().noquote() << metadata;
            if (d->error == Error::NoError) d->error = Error::InvalidMetadata;
            return false;
        }
        const QJsonObject object = metadata.toObject();
        qCDebug(d->lc).noquote() << tr("Processing %n metadata entry(s)", nullptr, object.length());
        for (auto iter = object.constBegin(); iter != object.constEnd(); ++iter) {
            d->allMetadata.insert(iter.key(), iter.value());
        }
    }
    // Process the (optional) shapes.
    const QJsonValue shapes = ast.value(QStringLiteral("shapes"));
    if (shapes != QJsonValue::Undefined) {
        if (!shapes.isObject()) {
            qCCritical(d->lc).noquote() << tr("Smithy AST shapes is not an object");
            if (d->error == Error::NoError) d->error = Error::InvalidShapes;
            return false;
        }
        const QJsonObject object = shapes.toObject();
        qCDebug(d->lc).noquote() << tr("Processing %n shape(s)", nullptr, object.length());
        for (auto iter = object.constBegin(); iter != object.constEnd(); ++iter) {
            const ShapeId shapeId(iter.key());
            if (!shapeId.isValid()) {
                qCCritical(d->lc).noquote() << tr("Failed to parse shape ID %1").arg(iter.key());
                if (d->error == Error::NoError) d->error = Error::InvalidShapeId;
                return false;
            }
            if (!shapeId.hasNameSpace()) {
                qCCritical(d->lc).noquote() << tr("Shape ID %1 has no namespace").arg(iter.key());
                if (d->error == Error::NoError) d->error = Error::InvalidShapeId;
                return false;
            }
            if (!iter.value().isObject()) {
                qCCritical(d->lc).noquote() << tr("Shape %1 is not a JSON object").arg(iter.key());
                if (d->error == Error::NoError) d->error = Error::InvalidShape;
                return false;
            }
            qCDebug(d->lc).noquote() << tr("Processing shape %1").arg(shapeId.toString());
            const Shape shape{iter.value().toObject(), shapeId};
            if (!shape.isValid()) {
                qCCritical(d->lc).noquote() << tr("Failed to process shape %1").arg(iter.key());
                if (d->error == Error::NoError) d->error = Error::InvalidShape;
                return false;
            }
            d->allShapes.insert(iter.key(), shape);
        }
    }
    return true;
}
References ShapeId::hasNameSpace(), QJsonValue::isObject(), ShapeId::isValid(), QJsonObject::keys(), QVersionNumber::majorVersion(), shapes(), QJsonValue::toObject(), ShapeId::toString(), QVersionNumber::toString(), and QJsonObject::value().
isValid()
bool Model::isValid () const
Definition at line 211 of file model.cpp.
{
    Q_D(const Model);
    return (d->error == Error::NoError);
}
metadata()
QJsonObject Model::metadata () const
Definition at line 217 of file model.cpp.
{
    Q_D(const Model);
    return d->mergedMetadata;
}
operator=() [1/2]
Model & Model::operator= (const Model && model)
Definition at line 65 of file model.cpp.
{
    Q_D(Model);
    d->error = std::move(model.d_ptr->error);
    d->mergedMetadata = std::move(model.d_ptr->mergedMetadata);
    d->mergedShapes = std::move(model.d_ptr->mergedShapes);
    d->allMetadata = std::move(model.d_ptr->allMetadata);
    d->allShapes = std::move(model.d_ptr->allShapes);
    return *this;
}
operator=() [2/2]
Model & Model::operator= (const Model & model)
Definition at line 54 of file model.cpp.
{
    Q_D(Model);
    d->error = model.d_ptr->error;
    d->mergedMetadata = model.d_ptr->mergedMetadata;
    d->mergedShapes = model.d_ptr->mergedShapes;
    d->allMetadata = model.d_ptr->allMetadata;
    d->allShapes = model.d_ptr->allShapes;
    return *this;
}
shapes()
QHash< ShapeId, Shape > Model::shapes (const Shape::Type & type = Shape::Type::Undefined) const
Todo:
this should be d->mergedShapes, but using allShapes while finish() is incomplete.
Definition at line 223 of file model.cpp.
{
    Q_D(const Model);
    if (type == Shape::Type::Undefined) {
        return d->mergedShapes;
    }
    QHash<ShapeId, Shape> shapes;
    /// \todo this should be d->mergedShapes, but using allShapes while finish() is incomplete.
    for (auto iter = d->allShapes.constBegin(); iter != d->allShapes.constEnd(); ++iter) {
        if (iter.value().type() == type) {
            shapes.insert(iter.key(), iter.value());
        }
    }
    return shapes;
}
References QHash::insert(), shapes(), and Shape::Undefined.
Referenced by insert(), and shapes().
Member Data Documentation
d_ptr
ModelPrivate* Model::d_ptr protected
Internal d-pointer.
Definition at line 60 of file model.h.
Referenced by ~Model().
The documentation for this class was generated from the following files:
model.h
model.cpp